apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-files-nginx-deployment
  labels:
    app: azure-files-nginx-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: azure-files-nginx-app
  template:
    metadata:
      labels:
        app: azure-files-nginx-app
    spec:
      containers:
        - name: azure-files-nginx-app
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html/app"
              name: my-azurefile-volume
          imagePullPolicy: Always
      volumes:
        - name: my-azurefile-volume
          persistentVolumeClaim:
            claimName: my-azurefile-pvc