apiVersion: v1
kind: Service
metadata:
  name: myapp-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - name: http
      port: 80
      targetPort: 80 #container port